name: Build

on:
  workflow_call:

env:
  APP_NAME: release

jobs:
  build_windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            label: windows-x86_64

    steps:
      - name: 检出仓库
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: 设置 rust
        uses: puniyu/setup-rust@5bef47975285e477b672ce87764f851fbb5fd6ab # main
        with:
          target: ${{ matrix.platform.target }}
          cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 构建
        run: |
          cargo build --release --bin ${{ env.APP_NAME }} --target ${{ matrix.platform.target }}
          
      - name: 创建存档文件
        uses: a7ul/tar-action@ed9cbd44fc9276db29ea2fb1f8adf3d7e0691589 # v1.2.0
        with:
          command: c
          files: |
            ${{ env.APP_NAME }}.exe
          cwd: target/${{ matrix.platform.target }}/release
          outPath: ${{ env.APP_NAME }}-${{ matrix.platform.target }}.tar.gz

      - name: 上传构建产物
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-${{ matrix.platform.target }}"
          path: |
            ${{ env.APP_NAME }}-${{ matrix.platform.target }}.tar.gz

  build_macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-latest
            target: x86_64-apple-darwin
            label: macos-x86_64
          - runner: macos-latest
            target: aarch64-apple-darwin
            label: macos-aarch64

    steps:
      - name: 检出仓库
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: 设置 rust
        uses: puniyu/setup-rust@5bef47975285e477b672ce87764f851fbb5fd6ab # main
        with:
          target: ${{ matrix.platform.target }}
          cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 构建
        run: |
          cargo build --release --bin ${{ env.APP_NAME }} --target ${{ matrix.platform.target }}
          
      - name: 创建存档文件
        uses: a7ul/tar-action@ed9cbd44fc9276db29ea2fb1f8adf3d7e0691589 # v1.2.0
        with:
          command: c
          files: |
            ${{ env.APP_NAME }}
          cwd: target/${{ matrix.platform.target }}/release
          outPath: ${{ env.APP_NAME }}-${{ matrix.platform.target }}.tar.gz

      - name: 上传构建产物
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-${{ matrix.platform.target }}"
          path: |
            ${{ env.APP_NAME }}-${{ matrix.platform.target }}.tar.gz

  build_linux:
    runs-on: ${{ matrix.platform.runner }}
    container: ${{ matrix.platform.container }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            label: linux-x86_64
            container: ghcr.io/puniyu/debian:latest
          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            label: linux-aarch64
            container: ghcr.io/puniyu/debian:arm64

    steps:
      - name: 检出仓库
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: 设置 rust
        uses: puniyu/setup-rust@5bef47975285e477b672ce87764f851fbb5fd6ab # main
        with:
          target: ${{ matrix.platform.target }}
          cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 构建
        run: |
          cargo build --release --bin ${{ env.APP_NAME }} --target ${{ matrix.platform.target }}


      - name: 创建存档文件
        uses: a7ul/tar-action@ed9cbd44fc9276db29ea2fb1f8adf3d7e0691589 # v1.2.0
        with:
          command: c
          files: |
            ${{ env.APP_NAME }}
          cwd: target/${{ matrix.platform.target }}/release
          outPath: ${{ env.APP_NAME }}-${{ matrix.platform.target }}.tar.gz

      - name: 上传构建产物
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ env.APP_NAME }}-${{ matrix.platform.target }}"
          path: |
            ${{ env.APP_NAME }}-${{ matrix.platform.target }}.tar.gz